/** 函数目录（EXEC-003 §4 契约冻结，新增 additive）：前端提示与文档单点来源。
 *  纯数据无 Node 依赖——客户端组件可安全 import（functions.ts 引擎实现依赖 node:crypto，
 *  不可进入浏览器 bundle）。 */
export const FUNCTION_CATALOG: {
  group: "engine" | "data" | "pipe";
  name: string;
  syntax: string;
  example: string;
  description: string;
}[] = [
  {
    group: "engine",
    name: "__counter",
    syntax: "${__counter(key)}",
    example: "${__counter(order)}",
    description: "任务内自增计数（按 key 分组，1 起）",
  },
  {
    group: "engine",
    name: "__random",
    syntax: "${__random(min,max)}",
    example: "${__random(1,9)}",
    description: "区间随机整数",
  },
  {
    group: "engine",
    name: "__UUID",
    syntax: "${__UUID()}",
    example: "${__UUID()}",
    description: "随机 UUID v4",
  },
  {
    group: "engine",
    name: "__time",
    syntax: "${__time(pattern)}",
    example: "${__time(yyyy-MM-dd)}",
    description: "当前时间格式化",
  },
  {
    group: "engine",
    name: "__timeShift",
    syntax: "${__timeShift(sec,pattern)}",
    example: "${__timeShift(3600,HH:mm)}",
    description: "偏移秒数后的时间",
  },
  {
    group: "engine",
    name: "__digest",
    syntax: "${__digest(algo,text)}",
    example: "${__digest(md5,abc)}",
    description: "摘要（md5/sha1/sha256）",
  },
  {
    group: "engine",
    name: "__base64",
    syntax: "${__base64(text)}",
    example: "${__base64(hello)}",
    description: "Base64 编码",
  },
  {
    group: "engine",
    name: "__urlEncode",
    syntax: "${__urlEncode(text)}",
    example: "${__urlEncode(a b)}",
    description: "URL 编码",
  },
  {
    group: "engine",
    name: "__isVarDefined",
    syntax: "${__isVarDefined(name)}",
    example: "${__isVarDefined(token)}",
    description: "变量是否已定义（true/false）",
  },
  {
    group: "engine",
    name: "__threadName",
    syntax: "${__threadName()}",
    example: "${__threadName()}",
    description: "场景名标识",
  },
  {
    group: "data",
    name: "@string",
    syntax: "@string(n)",
    example: "@string(8)",
    description: "随机小写字母串",
  },
  {
    group: "data",
    name: "@integer",
    syntax: "@integer(min,max)",
    example: "@integer(18,60)",
    description: "随机整数",
  },
  {
    group: "data",
    name: "@float",
    syntax: "@float(min,max)",
    example: "@float(0,1)",
    description: "随机浮点（两位）",
  },
  {
    group: "data",
    name: "@name",
    syntax: "@name()",
    example: "@name()",
    description: "随机中文姓名",
  },
  {
    group: "data",
    name: "@email",
    syntax: "@email()",
    example: "@email()",
    description: "随机邮箱",
  },
  {
    group: "data",
    name: "@phone",
    syntax: "@phone()",
    example: "@phone()",
    description: "随机手机号（13 段）",
  },
  {
    group: "data",
    name: "@date",
    syntax: "@date(pattern)",
    example: "@date(yyyy-MM-dd)",
    description: "随机日期（2020 起）",
  },
  {
    group: "data",
    name: "@datetime",
    syntax: "@datetime()",
    example: "@datetime()",
    description: "随机日期时间",
  },
  {
    group: "data",
    name: "@address",
    syntax: "@address()",
    example: "@address()",
    description: "随机省市",
  },
  {
    group: "data",
    name: "@idcard",
    syntax: "@idcard()",
    example: "@idcard()",
    description: "合规校验位身份证号",
  },
  {
    group: "data",
    name: "@regexp",
    syntax: "@regexp(re,text)",
    example: "@regexp(\\d+,abc123)",
    description: "正则首匹配（失败原样）",
  },
  {
    group: "data",
    name: "@pick",
    syntax: "@pick(a,b,c)",
    example: "@pick(A,B,O)",
    description: "列表随机取一",
  },
  {
    group: "pipe",
    name: "md5",
    syntax: "${var|md5}",
    example: "${token|md5}",
    description: "MD5 摘要",
  },
  {
    group: "pipe",
    name: "sha256",
    syntax: "${var|sha256}",
    example: "${token|sha256}",
    description: "SHA256 摘要",
  },
  {
    group: "pipe",
    name: "base64",
    syntax: "${var|base64}",
    example: "${token|base64}",
    description: "Base64",
  },
  {
    group: "pipe",
    name: "substr",
    syntax: "${var|substr(0,6)}",
    example: "${token|substr(0,6)}",
    description: "子串",
  },
  {
    group: "pipe",
    name: "toUpperCase",
    syntax: "${var|toUpperCase}",
    example: "${name|toUpperCase}",
    description: "大写",
  },
  {
    group: "pipe",
    name: "toLowerCase",
    syntax: "${var|toLowerCase}",
    example: "${name|toLowerCase}",
    description: "小写",
  },
  {
    group: "pipe",
    name: "trim",
    syntax: "${var|trim}",
    example: "${name|trim}",
    description: "去首尾空白",
  },
  {
    group: "pipe",
    name: "default",
    syntax: "${var|default(v)}",
    example: "${host|default(localhost)}",
    description: "空值兜底",
  },
];
