// Code generated by scripts/gen-cli-services.mjs from packages/api-client/src/generated/openapi.json.
// 门禁 4（Go 侧）：服务命令禁止手写接口路径——一律引用本文件常量；改动端点先改 OpenAPI 快照再重新生成。
// CLI-001 §4：--check 模式供 CI 校验 diff（对齐 gen-openapi --check 口径）。
package apidef

const (
	GET_personal_projects = "/api/v1/personal/projects" // GET
	GET_personal_me = "/api/v1/personal/me" // GET
	GET_projects_projectId_cases = "/api/v1/projects/{projectId}/cases" // GET
	POST_projects_projectId_cases = "/api/v1/projects/{projectId}/cases" // POST
	GET_projects_projectId_cases_caseId = "/api/v1/projects/{projectId}/cases/{caseId}" // GET
	PUT_projects_projectId_cases_caseId = "/api/v1/projects/{projectId}/cases/{caseId}" // PUT
	DELETE_projects_projectId_cases_caseId = "/api/v1/projects/{projectId}/cases/{caseId}" // DELETE
	GET_projects_projectId_apis = "/api/v1/projects/{projectId}/apis" // GET
	GET_projects_projectId_apis_apiId_cases = "/api/v1/projects/{projectId}/apis/{apiId}/cases" // GET
	POST_projects_projectId_apis_apiId_cases_execute = "/api/v1/projects/{projectId}/apis/{apiId}/cases/execute" // POST
	GET_projects_projectId_environments = "/api/v1/projects/{projectId}/environments" // GET
	GET_projects_projectId_scenarios = "/api/v1/projects/{projectId}/scenarios" // GET
	POST_projects_projectId_scenarios_id_execute = "/api/v1/projects/{projectId}/scenarios/{id}/execute" // POST
	GET_projects_projectId_plans = "/api/v1/projects/{projectId}/plans" // GET
	GET_projects_projectId_plans_planId = "/api/v1/projects/{projectId}/plans/{planId}" // GET
	POST_projects_projectId_plans_planId_execute = "/api/v1/projects/{projectId}/plans/{planId}/execute" // POST
	GET_projects_projectId_exec_tasks = "/api/v1/projects/{projectId}/exec-tasks" // GET
	POST_projects_projectId_exec_tasks_taskId_stop = "/api/v1/projects/{projectId}/exec-tasks/{taskId}/stop" // POST
	GET_open_exec_taskId = "/api/v1/open/exec/{taskId}" // GET
	GET_open_exec_taskId_report = "/api/v1/open/exec/{taskId}/report" // GET
)
